### PR TITLE
Initial support for year, month, day, etc. attributes of DatetimeIndex.

### PR DESCRIPTION
**Pull request by DrTodd13**
Initial comments please.

### CODE REVIEW

**Comment by ehsantn** [comment]
Thanks. Looks good to me. We can merge when build passes if you are done.

**Comment by DrTodd13** [comment]
Can't think of anything else to do there at the moment so if the build passes then we can merge.

**Comment by ehsantn** [comment]
Ok, thanks.

**Comment by ehsantn** [comment]
Merging. The tests are just exceeding Travic-CI time limit.

**Pull request merged**
